import hljs from "highlight.js";
import { ViewHook } from "phoenix_live_view";

import { updateLineNumbers } from "./update_line_numbers";

type CodeBlock = HTMLElement | null;
interface Highlight extends ViewHook {
  getSyntaxType: (name: string) => void;
  trimCodeBlock: (codeBlock: CodeBlock) => NonNullable<CodeBlock>;
}

const Highlight = {
  mounted(this: Highlight) {
    const name = this.el.getAttribute("data-name");
    const codeBlock: CodeBlock = this.el.querySelector("pre code");

    if (name && codeBlock) {
      codeBlock.className = codeBlock.className.replace(/language-\S+/g, "");
      codeBlock.classList.add(`language-${this.getSyntaxType(name)}`);

      const trimmed: HTMLElement = this.trimCodeBlock(codeBlock);
      hljs.highlightElement(codeBlock);
      if (trimmed.textContent) updateLineNumbers(trimmed.textContent);
    }
  },

  getSyntaxType(name) {
    const extension = name.split(".").pop();
    switch (extension) {
      case "asc":
      case "ash":
        return "ags-script";
      case "mod":
        return "ampl";
      case "g4":
        return "antlr";
      case "apib":
        return "api-blueprint";
      case "dyalog":
        return "apl";
      case "asax":
      case "ascx":
      case "ashx":
      case "asmx":
      case "aspx":
      case "axd":
        return "asp";
      case "dats":
      case "hats":
      case "sats":
        return "ats";
      case "as":
        return "actionscript";
      case "adb":
      case "ads":
        return "ada";
      case "als":
        return "alloy";
      case "vhost":
        return "apacheconf";
      case "cls":
        return "apex";
      case "scpt":
        return "applescript";
      case "ino":
        return "arduino";
      case "adoc":
        return "asciidoc";
      case "aj":
        return "aspectj";
      case "asm":
      case "a51":
      case "inc":
      case "nasm":
        return "assembly";
      case "aug":
        return "augeas";
      case "ahk":
      case "ahkl":
        return "autohotkey";
      case "au3":
        return "autoit";
      case "auk":
      case "gawk":
      case "mawk":
      case "nawk":
        return "awk";
      case "bat":
      case "cmd":
        return "batchfile";
      case "bb":
        return "bitbake";
      case "decls":
        return "blitzbasic";
      case "bmx":
        return "blitzmax";
      case "bsv":
        return "bluespec";
      case "b":
      case "bf":
        return "brainfuck";
      case "brs":
        return "brightscript";
      case "cats":
      case "h":
      case "idc":
      case "w":
        return "c";
      case "cs":
      case "cake":
      case "cshtml":
      case "csx":
        return "c#";
      case "cpp":
      case "cc":
      case "cp":
      case "cxx":
      case "h++":
      case "hh":
      case "hpp":
      case "hxx":
      case "inl":
      case "ipp":
      case "tcc":
      case "tpp":
        return "c++";
      case "chs":
        return "c2hs-haskell";
      case "clp":
        return "clips";
      case "cmake.in":
        return "cmake";
      case "cob":
      case "cbl":
      case "ccp":
      case "cpy":
        return "cobol";
      case "capnp":
        return "cap'n-proto";
      case "mss":
        return "cartocss";
      case "chpl":
        return "chapel";
      case "ch":
        return "charity";
      case "ck":
        return "chuck";
      case "clw":
        return "clarion";
      case "icl":
      case "dcl":
        return "clean";
      case "clj":
      case "boot":
      case "cl2":
      case "cljc":
      case "cljs":
      case "cljs.hl":
      case "cljscm":
      case "cljx":
      case "hic":
        return "clojure";
      case "coffee":
      case "_coffee":
      case "cjsx":
      case "cson":
      case "iced":
        return "coffeescript";
      case "cfm":
      case "cfml":
        return "coldfusion";
      case "cfc":
        return "coldfusion-cfc";
      case "lisp":
      case "asd":
      case "cl":
      case "l":
      case "lsp":
      case "ny":
      case "podsl":
      case "sexp":
        return "common-lisp";
      case "cps":
        return "component-pascal";
      case "v":
        return "coq";
      case "cppobjdump":
      case "c++-objdump":
      case "c++objdump":
      case "cxx-objdump":
        return "cpp-objdump";
      case "cr":
        return "crystal";
      case "feature":
        return "cucumber";
      case "cu":
      case "cuh":
        return "cuda";
      case "cy":
        return "cycript";
      case "pyx":
      case "pxd":
      case "pxi":
        return "cython";
      case "di":
        return "d";
      case "com":
        return "digital-command-language";
      case "zone":
      case "arpa":
        return "dns-zone";
      case "d":
        return "dtrace";
      case "darcspatch":
      case "dpatch":
        return "darcs-patch";
      case "patch":
        return "diff";
      case "djs":
        return "dogescript";
      case "dyl":
      case "intr":
      case "lid":
        return "dylan";
      case "E":
        return "e";
      case "eclxml":
        return "ecl";
      case "ecl":
        return "eclipse";
      case "sch":
      case "brd":
        return "eagle";
      case "epj":
        return "ecere-projects";
      case "e":
        return "eiffel";
      case "ex":
      case "exs":
        return "elixir";
      case "el":
      case "emacs":
      case "emacs.desktop":
        return "emacs-lisp";
      case "em":
        return "emberscript";
      case "erl":
      case "es":
      case "escript":
      case "hrl":
      case "xrl":
      case "yrl":
        return "erlang";
      case "fs":
      case "fsi":
      case "fsx":
        return "f#";
      case "fx":
        return "flux";
      case "f90":
      case "f":
      case "f03":
      case "f08":
      case "f77":
      case "f95":
      case "for":
      case "fpp":
        return "fortran";
      case "fy":
      case "fancypack":
        return "fancy";
      case "fan":
        return "fantom";
      case "eam.fs":
        return "formatted";
      case "fth":
      case "4th":
      case "fr":
      case "frt":
        return "forth";
      case "ftl":
        return "freemarker";
      case "g":
      case "gco":
      case "gcode":
        return "g-code";
      case "gms":
        return "gams";
      case "gd":
      case "gi":
      case "tst":
        return "gap";
      case "s":
      case "ms":
        return "gas";
      case "fp":
      case "frag":
      case "frg":
      case "fsh":
      case "fshader":
      case "geo":
      case "geom":
      case "glslv":
      case "gshader":
      case "shader":
      case "vert":
      case "vrx":
      case "vsh":
      case "vshader":
        return "glsl";
      case "gml":
        return "game-maker-language";
      case "kid":
        return "genshi";
      case "ebuild":
        return "gentoo-ebuild";
      case "eclass":
        return "gentoo-eclass";
      case "po":
      case "pot":
        return "gettext-catalog";
      case "glf":
        return "glyph";
      case "gp":
      case "gnu":
      case "plot":
      case "plt":
        return "gnuplot";
      case "gs":
      case "gst":
      case "gsx":
      case "vark":
        return "gosu";
      case "gf":
        return "grammatical-framework";
      case "dot":
      case "gv":
        return "graphviz-(dot)";
      case "man":
      case "1":
      case "1in":
      case "1m":
      case "1x":
      case "2":
      case "3":
      case "3in":
      case "3m":
      case "3qt":
      case "3x":
      case "4":
      case "5":
      case "6":
      case "7":
      case "8":
      case "9":
      case "me":
      case "n":
      case "rno":
      case "roff":
        return "groff";
      case "grt":
      case "gtpl":
      case "gvy":
        return "groovy";
      case "gsp":
        return "groovy-server-pages";
      case "tf":
        return "hcl";
      case "fxh":
      case "hlsli":
        return "hlsl";
      case "htm":
      case "html.hl":
      case "st":
      case "xht":
      case "xhtml":
      case "mustache":
      case "jinja":
      case "eex":
      case "erb":
      case "erb.deface":
      case "phtml":
      case "heex":
        return "html";
      case "php":
        return "php";
      case "haml.deface":
        return "haml";
      case "hbs":
        return "handlebars";
      case "hb":
        return "harbour";
      case "hs":
      case "hsc":
        return "haskell";
      case "hx":
      case "hxsl":
        return "haxe";
      case "pro":
      case "dlm":
        return "idl";
      case "ipf":
        return "igor-pro";
      case "cfg":
      case "prefs":
      case "properties":
        return "ini";
      case "irclog":
      case "weechatlog":
        return "irc-log";
      case "idr":
      case "lidr":
        return "idris";
      case "ni":
      case "i7x":
        return "inform-7";
      case "iss":
        return "inno-setup";
      case "ik":
        return "ioke";
      case "thy":
        return "isabelle";
      case "ijs":
        return "j";
      case "flex":
        return "jflex";
      case "geojson":
      case "lock":
      case "topojson":
        return "json";
      case "jq":
        return "jsoniq";
      case "j":
        return "jasmin";
      case "jsp":
        return "java-server-pages";
      case "js":
      case "_js":
      case "bones":
      case "es6":
      case "jake":
      case "jsb":
      case "jscad":
      case "jsfl":
      case "jsm":
      case "jss":
      case "njs":
      case "pac":
      case "sjs":
      case "ssjs":
      case "sublime-build":
      case "sublime-commands":
      case "sublime-completions":
      case "sublime-keymap":
      case "sublime-macro":
      case "sublime-menu":
      case "sublime-mousemap":
      case "sublime-project":
      case "sublime-settings":
      case "sublime-theme":
      case "sublime-workspace":
      case "sublime_metrics":
      case "sublime_session":
      case "xsjs":
      case "xsjslib":
        return "javascript";
      case "jl":
        return "julia";
      case "ipynb":
        return "jupyter-notebook";
      case "kicad_pcb":
        return "kicad";
      case "kt":
      case "ktm":
      case "kts":
        return "kotlin";
      case "ll":
        return "llvm";
      case "lol":
        return "lolcode";
      case "lslp":
        return "lsl";
      case "lvproj":
        return "labview";
      case "las":
      case "lasso8":
      case "lasso9":
      case "ldml":
        return "lasso";
      case "hlean":
        return "lean";
      case "ly":
      case "ily":
        return "lilypond";
      case "m":
        return "limbo";
      case "ld":
      case "lds":
        return "linker-script";
      case "lagda":
        return "literate-agda";
      case "litcoffee":
        return "literate-coffeescript";
      case "lhs":
        return "literate-haskell";
      case "ls":
      case "_ls":
        return "livescript";
      case "xm":
      case "x":
      case "xi":
        return "logos";
      case "lgt":
        return "logtalk";
      case "fcgi":
      case "nse":
      case "pd_lua":
      case "rbxs":
      case "wlua":
        return "lua";
      case "mumps":
        return "m";
      case "m4":
        return "m4sugar";
      case "mcr":
        return "maxscript";
      case "mak":
      case "mk":
      case "mkfile":
        return "makefile";
      case "mao":
        return "mako";
      case "md":
      case "mkd":
      case "mkdn":
      case "mkdown":
      case "ron":
        return "markdown";
      case "cdf":
      case "ma":
      case "mt":
      case "nb":
      case "nbp":
      case "wl":
      case "wlt":
        return "mathematica";
      case "maxpat":
      case "maxhelp":
      case "maxproj":
      case "mxt":
      case "pat":
        return "max";
      case "wiki":
        return "mediawiki";
      case "moo":
        return "mercury";
      case "druby":
      case "duby":
      case "mir":
        return "mirah";
      case "mo":
        return "modelica";
      case "mms":
      case "mmk":
        return "module-management-system";
      case "moon":
        return "moonscript";
      case "myt":
        return "myghty";
      case "nsi":
      case "nsh":
        return "nsis";
      case "axs":
      case "axi":
        return "netlinx";
      case "axs.erb":
      case "axi.erb":
        return "netlinx+erb";
      case "nlogo":
        return "netlogo";
      case "nl":
        return "newlisp";
      case "nginxconf":
        return "nginx";
      case "nim":
        return "nimrod";
      case "numpyw":
      case "numsc":
        return "numpy";
      case "ml":
      case "eliom":
      case "eliomi":
      case "ml4":
      case "mli":
      case "mll":
      case "mly":
        return "ocaml";
      case "mm":
        return "objective-c++";
      case "sj":
        return "objective-j";
      case "p":
        return "openedge-abl";
      case "scad":
        return "openscad";
      case "oxh":
      case "oxo":
        return "ox";
      case "pwn":
        return "pawn";
      case "aw":
      case "ctp":
      case "php3":
      case "php4":
      case "php5":
      case "phps":
      case "phpt":
        return "php";
      case "pls":
      case "pck":
      case "pkb":
      case "pks":
      case "plb":
      case "sql":
        return "plsql";
      case "pov":
        return "pov-ray-sdl";
      case "psc":
        return "papyrus";
      case "pasm":
        return "parrot-assembly";
      case "pir":
        return "parrot-internal-representation";
      case "pas":
      case "dfm":
      case "dpr":
      case "lpr":
      case "pp":
        return "pascal";
      case "pl":
      case "al":
      case "cgi":
      case "ph":
      case "plx":
      case "pm":
      case "pod":
      case "psgi":
      case "t":
        return "perl";
      case "6pl":
      case "6pm":
      case "nqp":
      case "p6":
      case "p6l":
      case "p6m":
      case "pl6":
      case "pm6":
        return "perl6";
      case "pkl":
        return "pickle";
      case "pig":
        return "piglatin";
      case "pmod":
        return "pike";
      case "pogo":
        return "pogoscript";
      case "ps":
      case "eps":
        return "postscript";
      case "ps1":
      case "psd1":
      case "psm1":
        return "powershell";
      case "pde":
        return "processing";
      case "yap":
        return "prolog";
      case "spin":
        return "propeller-spin";
      case "proto":
        return "protocol-buffer";
      case "pub":
        return "public-key";
      case "pd":
        return "pure-data";
      case "pb":
      case "pbi":
        return "purebasic";
      case "purs":
        return "purescript";
      case "py":
      case "bzl":
      case "gyp":
      case "lmi":
      case "pyde":
      case "pyp":
      case "pyt":
      case "pyw":
      case "rpy":
      case "tac":
      case "wsgi":
      case "xpy":
        return "python";
      case "pytb":
        return "python-traceback";
      case "qbs":
        return "qml";
      case "pri":
        return "qmake";
      case "rd":
      case "rsx":
        return "r";
      case "rbbas":
      case "rbfrm":
      case "rbmnu":
      case "rbres":
      case "rbtbar":
      case "rbuistate":
        return "realbasic";
      case "rmd":
        return "rmarkdown";
      case "rkt":
      case "rktd":
      case "rktl":
      case "scrbl":
        return "racket";
      case "rl":
        return "ragel-in-ruby-host";
      case "raw":
        return "raw-token-data";
      case "reb":
      case "r":
      case "r2":
      case "r3":
        return "rebol";
      case "reds":
        return "red";
      case "cw":
        return "redcode";
      case "rs":
      case "rsh":
        return "renderscript";
      case "robot":
        return "robotframework";
      case "rg":
        return "rouge";
      case "rb":
      case "builder":
      case "gemspec":
      case "god":
      case "irbrc":
      case "jbuilder":
      case "mspec":
      case "pluginspec":
      case "podspec":
      case "rabl":
      case "rake":
      case "rbuild":
      case "rbw":
      case "rbx":
      case "ru":
      case "thor":
      case "watchr":
        return "ruby";
      case "rs.in":
        return "rust";
      case "smt2":
        return "smt";
      case "rq":
        return "sparql";
      case "hqf":
        return "sqf";
      case "cql":
      case "ddl":
      case "prc":
      case "tab":
      case "udf":
      case "viw":
        return "sql";
      case "db2":
        return "sqlpl";
      case "sagews":
        return "sage";
      case "sls":
        return "saltstack";
      case "sbt":
      case "sc":
        return "scala";
      case "scm":
      case "sld":
      case "sps":
      case "ss":
        return "scheme";
      case "sci":
      case "sce":
        return "scilab";
      case "sh":
      case "bash":
      case "bats":
      case "command":
      case "ksh":
      case "sh.in":
      case "tmux":
      case "tool":
      case "zsh":
        return "shell";
      case "sh-session":
        return "shellsession";
      case "sl":
        return "slash";
      case "tpl":
        return "smarty";
      case "sp":
      case "sma":
        return "sourcepawn";
      case "nut":
        return "squirrel";
      case "ML":
      case "fun":
      case "sig":
      case "sml":
        return "standard-ml";
      case "do":
      case "ado":
      case "doh":
      case "ihlp":
      case "mata":
      case "matah":
      case "sthlp":
        return "stata";
      case "styl":
        return "stylus";
      case "scd":
        return "supercollider";
      case "sv":
      case "svh":
      case "vh":
        return "systemverilog";
      case "adp":
      case "tm":
        return "tcl";
      case "csh":
        return "tcsh";
      case "aux":
      case "bbx":
      case "bib":
      case "cbx":
      case "dtx":
      case "ins":
      case "lbx":
      case "ltx":
      case "mkii":
      case "mkiv":
      case "mkvi":
      case "sty":
      case "toc":
        return "tex";
      case "txt":
      case "ncl":
      case "no":
        return "text";
      case "tu":
        return "turing";
      case "ttl":
        return "turtle";
      case "ts":
      case "tsx":
        return "typescript";
      case "upc":
        return "unified-parallel-c";
      case "anim":
      case "asset":
      case "mat":
      case "meta":
      case "prefab":
      case "unity":
        return "unity3d-asset";
      case "uc":
        return "unrealscript";
      case "ur":
      case "urs":
        return "urweb";
      case "vhd":
      case "vhf":
      case "vhi":
      case "vho":
      case "vhs":
      case "vht":
      case "vhw":
        return "vhdl";
      case "vapi":
        return "vala";
      case "veo":
        return "verilog";
      case "vim":
        return "viml";
      case "vb":
      case "bas":
      case "frm":
      case "frx":
      case "vba":
      case "vbhtml":
      case "vbs":
        return "visual-basic";
      case "owl":
        return "web-ontology-language";
      case "ant":
      case "axml":
      case "ccxml":
      case "clixml":
      case "cproject":
      case "csl":
      case "csproj":
      case "ct":
      case "dita":
      case "ditamap":
      case "ditaval":
      case "dll.config":
      case "dotsettings":
      case "filters":
      case "fsproj":
      case "fxml":
      case "glade":
      case "grxml":
      case "iml":
      case "ivy":
      case "jelly":
      case "jsproj":
      case "kml":
      case "launch":
      case "mdpolicy":
      case "mxml":
      case "nproj":
      case "nuspec":
      case "odd":
      case "osm":
      case "plist":
      case "props":
      case "ps1xml":
      case "psc1":
      case "pt":
      case "rdf":
      case "rss":
      case "scxml":
      case "srdf":
      case "storyboard":
      case "stTheme":
      case "sublime-snippet":
      case "targets":
      case "tmCommand":
      case "tml":
      case "tmLanguage":
      case "tmPreferences":
      case "tmSnippet":
      case "tmTheme":
      case "ui":
      case "urdf":
      case "ux":
      case "vbproj":
      case "vcxproj":
      case "vssettings":
      case "vxml":
      case "wsdl":
      case "wsf":
      case "wxi":
      case "wxl":
      case "wxs":
      case "x3d":
      case "xacro":
      case "xaml":
      case "xib":
      case "xlf":
      case "xliff":
      case "xmi":
      case "xml.dist":
      case "xproj":
      case "xsd":
      case "xul":
      case "zcml":
        return "xml";
      case "xsp-config":
      case "xsp.metadata":
        return "xpages";
      case "xpl":
        return "xproc";
      case "xq":
      case "xql":
      case "xqm":
      case "xqy":
        return "xquery";
      case "xsl":
        return "xslt";
      case "xojo_code":
      case "xojo_menu":
      case "xojo_report":
      case "xojo_script":
      case "xojo_toolbar":
      case "xojo_window":
        return "xojo";
      case "yml":
      case "reek":
      case "rviz":
      case "sublime-syntax":
      case "syntax":
      case "yaml-tmlanguage":
        return "yaml";
      case "y":
      case "yy":
        return "yacc";
      case "zep":
        return "zephir";
      case "zmpl":
      case "zpl":
        return "zimpl";
      case "desktop.in":
        return "desktop";
      case "eh":
        return "ec";
      case "mu":
        return "mupad";
      case "nc":
        return "nesc";
      case "rst":
      case "rest":
      case "rest.txt":
      case "rst.txt":
        return "restructuredtext";
      case "prg":
      case "prw":
        return "xbase";
      default:
        return extension;
    }
  },

  trimCodeBlock(codeBlock: HTMLElement): HTMLElement {
    const lines = codeBlock.textContent?.split("\n");
    if (lines && lines.length > 2) {
      lines.shift();
      lines.pop();
    }

    codeBlock.textContent = lines?.join("\n") ?? "";
    return codeBlock;
  },
};

export default Highlight;
